### ISSUE TITLE
Functie: Tekst

### ISSUE THREAD

**Issue by AndriesZ** [AndriesZ/VGA_Aansturing#7]
Er moet een tekst op het scherm weer gegeven worden met de volgende argumenten:
- [x] x
- [x] y
- [x] string
- [ ] Bold/ cursive
- [x] letterype
- [x] size
- [ ] knipperend

**Comment by koentie96** [comment]
Update 28-05: Veel tijd verneukt aan 'bitmaps aan elkaar plakken'. Het idee is nu om bestaande jpeg's van fonts in paint in gelijke delen te verdelen. Eén font (weliswaar zonder bold, cursive, knipperen of variabele grootte) werkt nu goed.

**Comment by koentie96** [comment]
Update 30-05: Nu twee fonts beschikbaar: één zwarte en één met vrolijke kleurtjes. Ik ben nog niet begonnen aan knipperen of cursief.
