### ISSUE TITLE
Functie: Bitmaps

### ISSUE THREAD

**Issue by AndriesZ** [AndriesZ/VGA_Aansturing#9]
- [x] Moet vanuit flashgeheugen van de ARM op scherm geschreven worden
- [x] minimaal pijl (4 richtingen), smiley (boos, blij)
- [x] bmp-naam/id, x,y-positie

**Comment by koentie96** [comment]
Update 15-05: data schrijven naar flashgeheugen lijkt te lukken. Bij het lezen van het flashgeheugen krijg ik echter maar de helft terug van wat zou moeten.

**Comment by koentie96** [comment]
Update 16-05: data lezen/schrijven van flashgeheugen lukt nu (probleem was het niet leeghalen van de te schrijven adressen)

**Comment by koentie96** [comment]
Update 19-05: Bitmap lukt, alleen de achtergrond blijft nu niet wat hij moet zijn.

**Comment by koentie96** [comment]
Update (2) 19-05: Bitmap werkt! Alleen nog alles in een headerfile plaatsen en deze taak is afgerond.

**Comment by koentie96** [comment]
Update 22-5: Functie werkt!
